#ifndef GLOBAL_H
#define GLOBAL_H
#include <QApplication>
#include <QObject>
#include <QWidget>
#include <QTableWidget>
#include <QMouseEvent>
#include <QGraphicsView>
#include <QGraphicsItem>
#include <QGraphicsScene>
#include <QGraphicsItemAnimation>
#include <QPainter>
#include <QPainterPath>
#include <QRect>
#include <QRectF>
#include <QList>
#include <QFont>
#include <QStyleOption>
#include <QTime>
#include <QTimer>
#include <QSplitter>
#include <stdio.h>
#include <math.h>
#endif // GLOBAL_H
