######################################################################
# Automatically generated by qmake (3.0) ?? 4? 17 08:48:32 2015
######################################################################

TEMPLATE = app
TARGET = ship
INCLUDEPATH += .

# Input
HEADERS += ship.h \
    scale.h \
    global.h
SOURCES += main.cpp ship.cpp \
    scale.cpp

QT += widgets
